name: CI/CD - Backend (DockerHub + GHCR)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
    ##############################
    # 🔁 Checkout the repository
    ##############################
    - name: Checkout
      uses: actions/checkout@v3

    ##############################
    # 🐍 Setup Python
    ##############################
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    ##############################
    # ✅ Install dependencies and run tests
    ##############################
    - name: Install dependencies & Run tests
      run: |
        pip install -r requirements.txt
        pip install pytest flake8
        PYTHONPATH=. pytest        # Ensure Python finds app.py
        flake8 app.py

    ##############################
    # 🐳 DockerHub Build & Push
    ##############################
    - name: Build Docker image (DockerHub)
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/micro-notes-backend:latest .

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/micro-notes-backend:latest

    ##############################
    # 🐙 GitHub Container Registry (GHCR)
    ##############################
    - name: Tag image for GHCR
      run: docker tag ${{ secrets.DOCKER_USERNAME }}/micro-notes-backend:latest ghcr.io/${{ secrets.GHCR_USERNAME }}/micro-notes-backend:latest

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/micro-notes-backend:latest
