name: CI/CD - Backend (DockerHub + GHCR)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install deps + run tests
      run: |
        pip install -r requirements.txt
        pytest
        flake8 app.py

    # 🐳 DockerHub build + push
    - name: Build image for DockerHub
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/micro-notes-backend:latest .

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/micro-notes-backend:latest

    # 🐙 GHCR build + push
    - name: Build image for GHCR
      run: docker tag ${{ secrets.DOCKER_USERNAME }}/micro-notes-backend:latest ghcr.io/${{ secrets.GHCR_USERNAME }}/micro-notes-backend:latest

    - name: Login to GHCR
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Push to GHCR
      run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/micro-notes-backend:latest
